### ISSUE TITLE
Failed to transform artifact 'Lndmobile.aar (project :Lndmobile)' to match attributes {artifactType=android-manifest}

### ISSUE THREAD

**Issue by juantellez** [coreyphillips/bitbip#2]
Hi, when running react-native run-android it wont compile giving an error trying to transform artifact lndmobile.aar

I have windows 10

info JS server already running.
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform artifact 'Lndmobile.aar (project :Lndmobile)' to match attributes {artifactType=android-manifest}
      > Execution failed for IdentityTransform: C:\Users\juant\Documents\GitHub\bitbip\android\Lndmobile\Lndmobile.aar.
         > Transform output file C:\Users\juant\Documents\GitHub\bitbip\android\Lndmobile\Lndmobile.aar does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
54 actionable tasks: 1 executed, 53 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug
debug Error: Command failed: gradlew.bat app:installDebug
    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (C:\Users\juant\Documents\GitHub\bitbip\node_modules\@react-native-community\cli\build\commands\runAndroid\runOnAllDevices.js:58:39)
    at buildAndRun (C:\Users\juant\Documents\GitHub\bitbip\node_modules\@react-native-community\cli\build\commands\runAndroid\runAndroid.js:142:41)
    at then.result (C:\Users\juant\Documents\GitHub\bitbip\node_modules\@react-native-community\cli\build\commands\runAndroid\runAndroid.js:104:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by coreyphillips** [comment]
Hey @juantellez, the most recent [commit](https://github.com/coreyphillips/bitbip/commit/24085b43bd07e7f0710c7f493e6647c9b835e5cb) sets up Lightning so it's looking for the Lndmobile.aar file in `bitbip\android\Lndmobile\`. The current process to generate this file can be found [here](https://github.com/lightningnetwork/lnd/pull/3282).

LND isn't fully implemented in this app yet so if you prefer to just get this app up and running similar to what's available for testing on Testflight and the Play Store you can simply checkout the commit prior to the LND implementation like so:
```
git clone https://github.com/coreyphillips/bitbip
cd bitbip
git checkout 79d1e65879dac8dc2fd5bcd4401ec8e462100813
yarn install && cd nodejs-assets/nodejs-project && yarn install && cd ../../
react-native run-android
```
